accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.detail, name="detail"),
    path('addmovies/', views.add_movies, name="add_movies"),
    path('editmovies/<int:id>/', views.edit_movies, name="edit_movies"),
    path('deletemovies/<int:id>/', views.delete_movies, name="delete_movies"),
]

moviereview/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.http import HttpResponse

# Create your models here.

class Movie(models.Model):
    # fields for the movie table
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from  django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
       

main/forms.py
from django import forms
from .models import *

#movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'release_date', 'image')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
# Create your views here.
# registration
def register(request):
        if request.method == "POST":
            form = RegistrationForm(request.POST or None)
            # check if the form is valid
            if form.is_valid():
                user = form.save()

                # get the raw password
                raw_password = form.cleaned_data.get('password1')

                # authenticate the user
                user = authenticate(username=user.username, password=raw_password)

                # login the user
                login(request, user)

                return redirect("main:home")
        else:
            form = RegistrationForm()
        return render(request, "accounts/register.html", {"form": form})


# login
def login_user(request):
    # if request.user.is_authenticated:
    #     return redirect("main:home")
    # else:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']

            print(username, password)
            # check the credentials
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("main:home")
                else:
                    return render(request, 'accounts/login.html', {"error": "Your account has been disabled."})
            else:
                return render(request, 'accounts/login.html', {"error": "Invalid Username or Password. Try Again."})
        return render(request, 'accounts/login.html')

# logout user
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        print("Logged out succesfully")
        return redirect("accounts:login")
    else:
        return redirect("accounts:login")

main/views.py
import dataclasses
from pickle import NONE
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from .models import *
from .forms import *

# Create your views here.
def home(request):
    allMovies = Movie.objects.all()        
    print(allMovies)

    context = {
        "movies": allMovies,
    }

    return render(request, 'main/index.html', context)


# detail page
def detail(request, id):
    movie = Movie.objects.get(id=id) #select * from movie where id=id

    context = {
        "movie": movie
    }
    return render(request, 'main/details.html', context)

# add movies to the database
def add_movies(request):
    if request.method == "POST":
        form = MovieForm(request.POST or None)

        # check if form is valid
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
         form = MovieForm()
    return render(request, 'main/addmovies.html', {"form": form})

def edit_movies(request, id):

    movie = Movie.objects.get(id=id)

    if request.method == "POST":
        form = MovieForm(request.POST or None, instance=movie)

        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:detail", id)

    else:
        form = MovieForm(instance=movie)
    return render(request, 'main/addmovies.html', {"form": form})

def delete_movies(request, id):

    movie = Movie.objects.get(id=id)

    movie.delete()
    return redirect("main:home")
    

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Login to your account</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <label for="username">Username</label>
                <input type="text" placeholder="Enter your username" class="form-control" name="username">

                <label for="pasword">Password</label>
                <input type="password" placeholder="Enter your password" class="form-control" name="password">
                <br>

                {% if error %}
                    <i style="color: red;">{{ error }}</i>
                {% endif %}
                <input type="submit" value="Login" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Register an Account</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="Register" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/addmovies.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Movies</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="Add Movies" class="bt btn-dang">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">


    <title>Movie Recommender</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark text-white">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:home' %}">Movie Recommender</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:add_movies' %}">Add Movies</a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username }}
              </a>
                
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="">My Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              </li>
              
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
              </li>
              {% endif %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Genre
              </a>
                
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="">Comedy</a></li>
                  <li><a class="dropdown-item" href="">Action</a></li>
                  <li><a class="dropdown-item" href="">Fantasy</a></li>
                  <li><a class="dropdown-item" href="">Romantic</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Top-List</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    {% block content %}
    

    {% endblock %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container"
    <br>
    <div class="card">
        <div class="card-body">
            <div class="col-md-4">
                <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="text-centre">
                    {{ movie.name }}
                </h3>
                <p>{{ movie.averageRating }}</p>
                <h5>{{ movie.description }}</h5>
                <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">Edit Movie</a> 
                <a href="{% url 'main:delete_movies' movie.id %}" class="btn btn-danger">Delete Movie</a> 
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}

<br>
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                            <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            <h3 class="text-center">{{ movie.name }}</h3>
                            <i class="text-center">{{ movie.release_date }}</i>
                            <a href="{% url 'main:detail' movie.id %}">Read more</a>
                            </div>
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}